#!/bin/bash


grep -h "^void " ../../core/c/*.c | sed 's/^/\{/' | sed 's/$/\}/' | sed 's/_/\\_/g'> /tmp/Bv

grep -h "^void " ../../core/c/*.c  | sed 's/void \*//' | sed 's/void //' | awk -F\( '{ print "\\newcommand{\\cf" $1"}" }' | sed 's/_/UD/g'| sed 's/1/ONE/g'| sed 's/2/TWO/g' | sed 's/3/THREE/g' | sed 's/4/FOUR/g' | sed 's/5/FIVE/g' | sed 's/6/SIX/g'  | sed 's/7/SEVEN/g' | sed 's/8/EIGHT/g' | sed 's/9/NINE/g' > /tmp/Av

paste /tmp/Av /tmp/Bv| sed '/cfgenericUD/d' | sed '/cfucUD/d' | sed '/cfusUD/d'  | sed '/cflUD/d'  | sed '/cfulUD/d'  | sed '/cffUD/d' | sed '/cfdUD/d'| sort -u > ../build/doc/texinputs/cfvt.tex


rm /tmp/Av /tmp/Bv 

